name: Deploy to IONOS via SCP (with Insecure Cipher Debug)

on:
  push:
    branches:
      - main
      - touch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SCP to IONOS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          source: "."
          target: "Kaffee"
          use_insecure_cipher: true # <--- DIESE ZEILE HINZUFÜGEN!
          # debug: true # Diese Option existiert bei dieser Aktion wahrscheinlich nicht
